CREATE TABLE Auto (
	Targa VARCHAR(8) NOT NULL PRIMARY KEY,
	Marca VARCHAR(20) NOT NULL,
	Cilindrata INT NOT NULL,
	Potenza INT NOT NULL,
	CodF VARCHAR(16) NOT NULL FOREIGN KEY ([CodF]) REFERENCES [Proprietario]([CodF]),
	CodAss INT NOT NULL FOREIGN KEY ([CodAss]) REFERENCES [Assicurazione]([CodAss])
)

CREATE TABLE Proprietario (
	CodF VARCHAR(16) NOT NULL PRIMARY KEY,
	Nome VARCHAR(30) NOT NULL,
	Residenza VARCHAR(50) NOT NULL
)

CREATE TABLE Assicurazione (
	CodAss INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	Nome VARCHAR(30) NOT NULL,
	Sede VARCHAR(50) NOT NULL
)

CREATE TABLE Sinistro (
	CodS INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	Localita VARCHAR(50) NOT NULL,
	DataA date NOT NULL
)

CREATE TABLE AutoCounvolta (
	CodS INT NOT NULL FOREIGN KEY ([CodS]) REFERENCES [Sinistro]([CodS]),
	Targa VARCHAR(8) NOT NULL FOREIGN KEY ([Targa]) REFERENCES [Auto]([Targa]),
	CostoDanno DECIMAL(12, 2) NOT NULL,
	PRIMARY KEY (CodS, Targa)
)